version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rates_prod

  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
    depends_on:
      - migration
  migration:
    build: .
    command: /app/bin/demo eval Rates.ReleaseTasks.migrate()
    volumes:
      - /app
    links:
      - db
    depends_on:
      - db
