version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db
    # command: /rates/bin/demo eval Rates.ReleaseTasks.migrate()

  # migration:
  #   build: .
  #   command: /app/bin/demo eval Rates.ReleaseTasks.migrate()
  #   volumes:
  #     - /app
  #   links:
  #     - db
  #   depends_on:
  #     - db
