apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rates-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rates
    spec:
      containers:
        - name: rates
          image: banzay/rates
          ports:
            - containerPort: 4000
          args: ["start"]
          livenessProbe:
            httpGet:
              path: /api/health-check
              port: 4000
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: "postgres:10.1"
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
